kind = "web"
previewPath = "/"
title = "WorldwideRapidTaskForMoney"
version = "1.0.0"
id = "artifacts/wrtfm"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22144

[services.development]
run = "pnpm --filter @workspace/wrtfm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wrtfm", "run", "build" ]
serve = "static"
publicDir = "artifacts/wrtfm/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22144"
BASE_PATH = "/"
